# Pokemon Service Local Configuration
spring:
  application:
    name: pokemon-service

  # Config Server connection
  config:
    import: "optional:configserver:http://localhost:8888"

  datasource:
    url: jdbc:postgresql://localhost:5432/pokemon_db
    username: isyeibby
    password: '040042177'

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Fallback configuration (if Config Server is down)
server:
  port: 8081

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.pokemon.microservices: DEBUG
    root: INFO
