# API Gateway Configuration
server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Pokemon Service Routes
        - id: pokemon-service
          uri: lb://pokemon-service
          predicates:
            - Path=/api/pokemon/**
          filters:
            - StripPrefix=0

        # Trainer Service Routes
        - id: trainer-service
          uri: lb://trainer-service
          predicates:
            - Path=/api/trainers/**
          filters:
            - StripPrefix=0

        # Team Service Routes
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/teams/**
          filters:
            - StripPrefix=0

        # Config Server Routes (for monitoring)
        - id: config-server
          uri: lb://config-server
          predicates:
            - Path=/config/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG