# Team Service Configuration
server:
  port: 8083

spring:
  application:
    name: team-service

  datasource:
    url: jdbc:postgresql://localhost:5432/team_db
    username: team_user
    password: team_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Configuración específica de equipos
team:
  max-pokemon-per-team: 6
  max-teams-per-trainer: 10
  default-team-name: "Mi Equipo"

logging:
  level:
    com.pokemon.microservices.team: DEBUG