# Trainer Service Configuration
server:
  port: 8082

spring:
  application:
    name: trainer-service

  datasource:
    url: jdbc:postgresql://localhost:5432/trainer_db
    username: trainer_user
    password: trainer_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

# Configuración específica de captura de Pokemon
pokemon:
  capture:
    base-success-rate: 0.5
    level-bonus: 0.02
    max-attempts: 3
    cooldown-minutes: 5

logging:
  level:
    com.pokemon.microservices.trainer: DEBUG